# Generated by Django 3.0.1 on 2020-01-20 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Наименование организации')),
                ('icon', models.ImageField(default='topic_icon_default.png', upload_to='partners_icons', verbose_name='Иконка')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('service', models.CharField(max_length=200, verbose_name='Тип услуги, деятельность')),
                ('examples', models.TextField(verbose_name='Примеры работ')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Наименование организации')),
                ('icon', models.ImageField(default='topic_icon_default.png', upload_to='partners_icons', verbose_name='Иконка')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('service', models.CharField(max_length=200, verbose_name='Тип поставляемого оборудования')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
            },
        ),
    ]
