# Generated by Django 3.0.1 on 2020-01-21 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Субподрядчик', 'verbose_name_plural': 'Субподрядчики'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='contractor',
            name='examples',
            field=models.TextField(blank=True, verbose_name='Примеры работ'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='icon',
            field=models.ImageField(default='pertner_icon_default.png', upload_to='partners_icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Оценка'),
        ),
    ]
