# Generated by Django 3.0.1 on 2020-01-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20200121_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='service',
            field=models.TextField(verbose_name='Тип услуги, деятельность'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='icon',
            field=models.ImageField(default='pertner_icon_default.png', upload_to='partners_icons', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='service',
            field=models.TextField(verbose_name='Тип поставляемого оборудования'),
        ),
    ]
