# Generated by Django 3.0.1 on 2019-12-26 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20191226_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('link', models.TextField(blank=True, verbose_name='Ссылка')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('pub_date', models.CharField(blank=True, max_length=200, verbose_name='Дата публикации')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Литература',
                'verbose_name_plural': 'Литература',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя')),
                ('link', models.TextField(verbose_name='Ссылка')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Внешняя ссылка',
                'verbose_name_plural': 'Внешние ссылки',
            },
        ),
    ]
