# Generated by Django 3.0.1 on 2019-12-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_link_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='section_links',
        ),
        migrations.RemoveField(
            model_name='page',
            name='section_literature',
        ),
    ]
