# Generated by Django 3.0.1 on 2019-12-26 14:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191226_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Раздел'),
        ),
    ]
