# Generated by Django 3.0.1 on 2019-12-26 14:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20191226_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
