# Generated by Django 3.0.1 on 2020-01-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='alter_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Переименовать файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
