# Generated by Django 3.0.1 on 2020-01-11 09:46

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20200110_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(upload_to=pages.models.file_storage_path, verbose_name='Файл'),
        ),
    ]
