# Generated by Django 3.0.1 on 2020-01-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200111_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(upload_to='uploads', verbose_name='Файл'),
        ),
    ]
