# Generated by Django 3.0.1 on 2020-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20200122_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Программирование', 'Программирование 1'), ('Конструирование', 'Конструирование 1'), ('Управление проектами', 'Управление проектами 1'), ('Схемотехника', 'Схемотехника 1')], max_length=200, verbose_name='Название'),
        ),
    ]
