# Generated by Django 3.0.1 on 2020-01-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200122_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(None, '---------'), ('SOFT_DEV', 'Программирование'), ('CONSTRUCT', 'Конструирование'), ('PROJ_MANAG', 'Управление проектами'), ('CIRC_ENG', 'Схемотехника')], max_length=200, verbose_name='Название'),
        ),
    ]
