# Generated by Django 3.0.1 on 2020-01-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20200122_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(None, '---------'), ('SOFT_DEV', 'Программирование'), ('CONSTRUCT', 'Конструирование'), ('PROJ_MANAG', 'Управление проектами'), ('CIRC_ENG', 'Схемотехника'), ('PROC_SI', 'Процесс "Системная интеграция"')], max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
