# Generated by Django 3.0.1 on 2020-01-29 13:17

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_auto_20200123_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(max_length=500, upload_to=pages.models.file_storage_path, verbose_name='Файл'),
        ),
    ]
