# Generated by Django 3.0.1 on 2020-01-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileslibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(choices=[('RD', 'Нормативная документация'), ('AR', 'Литература')], default='RD', max_length=10, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
