# Generated by Django 3.0.1 on 2020-01-29 13:15

from django.db import migrations, models
import fileslibrary.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileslibrary', '0002_auto_20200129_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(max_length=500, upload_to=fileslibrary.models.file_storage_path, verbose_name='Файл'),
        ),
    ]
