# Generated by Django 3.0.1 on 2020-01-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maparealink',
            options={'verbose_name': 'Ссылка на карте процесса', 'verbose_name_plural': 'Ссылки на карте процесса'},
        ),
    ]
